name: Build APK

on:
  push:
    branches:
      - main  # Run workflow on push to the main branch
  pull_request:
    branches:
      - main  # Run workflow on pull requests to the main branch

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Use a valid Python version

      # Step 3: Install Buildozer and Dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config \
                                  zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev \
                                  libssl-dev build-essential ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev \
                                  libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
                                  libgstreamer1.0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good sqlite3 \
                                  libsqlite3-dev bzip2 libbz2-dev openssl libgdbm-dev liblzma-dev \
                                  libreadline-dev uuid-dev
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      # Step 4: Initialize Buildozer
      - name: Initialize Buildozer
        run: |
          buildozer init

      # Step 5: Build APK
      - name: Build APK
        run: |
          buildozer android debug

      # Step 6: Upload APK to GitHub Artifacts
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: bin/*.apk
